version: '3.3'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - discovery

  rabbitmq:
    image: "rabbitmq:3"

  redis:
    image: "redis:latest"

  discovery:
    image: "consul:1.8"
    environment:
      - CONSUL_LOCAL_CONFIG={"log_level":"info"}

  postgres-auth:
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  postgres-trips:
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  postgres-user-collections:
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - redis
      - postgres-auth
      - rabbitmq



  trips_0:
    build:
      context: ./trip
      dockerfile: Dockerfile
    depends_on:
      - discovery
      - api-gateway
      - postgres-trips
      - rabbitmq
      - redis

  trips_1:
    build:
      context: ./trip
      dockerfile: Dockerfile
    depends_on:
      - discovery
      - api-gateway
      - postgres-trips
      - rabbitmq
      - redis


  user-collections:
    build:
      context: ./user-collections
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery
      - postgres-user-collections
      - auth
      - rabbitmq
      - redis