FROM adoptopenjdk/openjdk11:alpine

COPY target/auth.jar .

CMD java -jar auth.jar



#https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/exercise-solutions/card-game/part-10/auth/Dockerfile