spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    add-mappings: false
  application:
    name: trips-service
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: rabbitmq
  datasource:
    url: "jdbc:postgresql://postgres-trips:5432/postgres"
    username: "postgres"
    password: "postgres"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: validate
  cloud:
    consul:
      host: discovery
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}